### ISSUE TITLE
Crash sometimes use adorners:Info for DataGridRow.

### ISSUE THREAD

**Issue by pgbo** [GuOrg/Gu.Wpf.Adorners#25]
The crash log is below:
```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 MS.Internal.Controls.TemplatedAdorner.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.Documents.AdornerLayer.MeasureOverride(Size constraint)
   在 System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   在 System.Windows.UIElement.Measure(Size availableSize)
   在 System.Windows.ContextLayoutManager.UpdateLayout()
   在 System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   在 System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   在 System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   在 System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   在 System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

And I use adorners:Info for DataGridRow like below :
```xml
<DataGrid.RowStyle>
    <Style BasedOn="{StaticResource DataGridRowDefault}" TargetType="DataGridRow">
        <Setter Property="adorners:Info.IsVisible">
            <Setter.Value>
                <MultiBinding Converter="{StaticResource Equal2BoolConverter}">
                    <Binding
                        Mode="OneWay"
                        Path="DataContext"
                        RelativeSource="{RelativeSource Self}" />
                    <Binding
                        ElementName="PageRoot"
                        FallbackValue="{x:Null}"
                        Mode="OneWay"
                        Path="DataContext.CurrentLowestPriceSellOrder" />
                </MultiBinding>
            </Setter.Value>
        </Setter>
        <Setter Property="adorners:Info.Template">
            <Setter.Value>
                <ControlTemplate>
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto" />
                            <RowDefinition Height="Auto" />
                        </Grid.RowDefinitions>
                        <Border
                            HorizontalAlignment="Stretch"
                            BorderBrush="{DynamicResource PrimaryBrush3}"
                            BorderThickness="0,0,0,1">
                            <AdornedElementPlaceholder />
                        </Border>
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
</DataGrid.RowStyle>
```

The DataGridRow Info.IsVisible is based on the equility of the row's DataContext and an ParentView's DataContext property(named CurrentLowestPriceSellOrder).

Because It doesn't happen very often, I wonder if there was a memory leak. Looking forward to your reply!

**Comment by JohanLarsson** [comment]
Thanks for reporting, I'll try to repro in an UI-test.

**Comment by JohanLarsson** [comment]
According to the stack trace it blows up [here](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/Controls/TemplatedAdorner.cs,140) for some reason. Only way I see that happening is if `_child` is null there for some reason.

**Comment by pgbo** [comment]
@JohanLarsson Thank you. I really don't know when and why `_child` become null. Do you have any Suggestions about this?

**Comment by JohanLarsson** [comment]
I'm thinking maybe it can have something to do with virtualization but that is just a shot in the dark.
I have not managed to reproduce the behavior yet.

**Comment by JohanLarsson** [comment]
Have a repro now, resizing the window triggers the NRE.

Problem is it is all framework code so not sure how to work around it.

**Comment by JohanLarsson** [comment]
Setting `EnableRowVirtualization="False"` solves it but it is not a nice solution.

**Comment by JohanLarsson** [comment]
https://github.com/dotnet/wpf/issues/234

**Comment by pgbo** [comment]
[https://github.com/GuOrg/Gu.Wpf.Adorners/commit/90868e02c1e9a3eb48d0518531710e7b38f536e3](Simplify repro. #25.) I use this demo, but not reproduce the behavior when resizing the window.

**Comment by JohanLarsson** [comment]
Released a new version: https://www.nuget.org/packages/Gu.Wpf.Adorners/1.5.1
Nuget needs a couple of minutes to index it. Please repoen the issue if the bug is not fixed.

**Comment by JohanLarsson** [comment]
Released a new version: https://www.nuget.org/packages/Gu.Wpf.Adorners/1.5.1
Nuget needs a couple of minutes to index it. Please repoen the issue if the bug is not fixed.

**Comment by JohanLarsson** [comment]
@pgbo chances are you pulled the repro after I committed the fix, let's hope that is what happened. If not re-open or create a new issue.

**Comment by stevenbrix** [comment]
@JohanLarsson does this repro in .NET Framework as well?

**Comment by JohanLarsson** [comment]
@stevenbrix How do you mean?

**Comment by stevenbrix** [comment]
If you retarget your app to .NET Framework 4.8 (instead of .NET Core 3) do you see the same behavior?

**Comment by JohanLarsson** [comment]
Is 4.8 released? I tried it with 4.7.2, the max version I have installed, the bug was there. Note that the bug may be due to me doing something dumb in this library.

If you want to try it yourself everything for the repro is in [this folder](https://github.com/GuOrg/Gu.Wpf.Adorners/tree/master/Gu.Wpf.Adorners.Demo/Windows/Issue25).
Note that you will only see the bug using [version 1.5.0](https://www.nuget.org/packages/Gu.Wpf.Adorners/1.5.0) of this library.

I wrote the UI-test like [this](https://github.com/GuOrg/Gu.Wpf.Adorners/blob/master/Gu.Wpf.Adorners.UiTests/Issue25WindowTests.cs#L18-L46)

**Comment by pgbo** [comment]
I'm foolish, I really don't how to use Gu.Wpf.Adorners.UiTests with visual studio. I can't run any test, and I can't find any test in Test Explorer. Do you use them in another way?

**Comment by JohanLarsson** [comment]
Do you have the [NUnit Testrunner extension](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter) installed?
Visual studio needs it to detect NUnit tests.

If you have Resharper installed the R# runner runs them by default.

Did you try the updated package on nuget? [v1.5.1](https://www.nuget.org/packages/Gu.Wpf.Adorners/1.5.1) is hopefully fixed for your scenario.

Don't hesitate to ask, we will help out so that you can run the tests.

**Comment by FoggyFinder** [comment]
> I'm foolish, I really don't how to use Gu.Wpf.Adorners.UiTests with visual studio. I can't run any test, and I can't find any test in Test Explorer.

If you have NUnit adapter then you have to uncheck the next setting:

![_testadapters](https://user-images.githubusercontent.com/16510738/50758605-52b67280-126b-11e9-9c97-d429fccff986.jpg)

Tools ->
    Options ->
        Test: _For improved performance, only use test adapters in test assembly folder or as specified in runsettings file_

Another option is to add the  `NUnit3TestAdapter` and, probably, also `Microsoft.NET.Test.Sdk` packages to project files. (I haven't tried this option by myself yet).

**Comment by JohanLarsson** [comment]
Ask more questions if you don't get it to work.
And if you have time please try the updated package and report if it solves the issue for you.

**Comment by pgbo** [comment]
Yes, it reproduced in your 1.5.0 test code. But reproduced in my project is not easy. I’ll take continuous concern.

**Comment by pgbo** [comment]
@Johan Larsson I’m glad to tell you my project never reproduce this bug again when upgade this framework to newest version!
