### ISSUE TITLE
Watermark transparency

### ISSUE THREAD

**Issue by Husky-s** [GuOrg/Gu.Wpf.Adorners#27]
Watermark does not bind transparency with TextBox or PasswordBox

**Comment by JohanLarsson** [comment]
Try:

```xaml
<Style x:Key="AdornerTextStyle" TargetType="{x:Type TextBlock}">
    <Setter Property="Opacity" Value="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type adorners:WatermarkAdorner}}, Path=AdornedElement.Opacity}" />
</Style>
```

And:

```xaml
<TextBox adorners:Watermark.Text="Some text"
         adorners:Watermark.TextStyle="{StaticResource AdornerTextStyle}"
         Opacity="{Binding ElementName=Slider, Path=Value}" />
<Slider Name="Slider"
        Maximum="1"
        Minimum="0"
        Value="0.5" />
```

**Comment by Husky-s** [comment]
![image](https://user-images.githubusercontent.com/31825139/60685786-bda8d500-9ead-11e9-8b22-5fcb59468178.png)
It does not work for me

**Comment by JohanLarsson** [comment]
Full sample:
```xaml
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:adorners="http://gu.se/Adorners"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignHeight="450"
        d:DesignWidth="800"
        mc:Ignorable="d">
    <Window.Resources>
        <Style x:Key="AdornerTextStyle" TargetType="{x:Type TextBlock}">
            <Setter Property="Opacity" Value="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type adorners:WatermarkAdorner}}, Path=AdornedElement.Opacity}" />
        </Style>
    </Window.Resources>
    <StackPanel>
        <TextBox adorners:Watermark.Text="Some text"
                 adorners:Watermark.TextStyle="{StaticResource AdornerTextStyle}"
                 Opacity="{Binding ElementName=Slider, Path=Value}" />
        <Slider Name="Slider"
                Maximum="1"
                Minimum="0"
                Value="0.5" />
    </StackPanel>
</Window>
```

^ works in Sweden from what I can tell.

**Comment by Husky-s** [comment]
I think watermark opacity does not change when I change opacity of the textbox through the code

**Comment by Husky-s** [comment]
I finally solved my problem!

**Comment by JohanLarsson** [comment]
What was the issue and what was the solution?

**Comment by Husky-s** [comment]
I misused my variable.
This code is solution.
`<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:adorners="http://gu.se/Adorners"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        d:DesignHeight="450"
        d:DesignWidth="800"
        mc:Ignorable="d">
    <Window.Resources>
        <Style x:Key="AdornerTextStyle" TargetType="{x:Type TextBlock}">
            <Setter Property="Opacity" Value="{Binding RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type adorners:WatermarkAdorner}}, Path=AdornedElement.Opacity}" />
        </Style>
    </Window.Resources>
    <StackPanel>
        <TextBox adorners:Watermark.Text="Some text"
                 adorners:Watermark.TextStyle="{StaticResource AdornerTextStyle}"
                 Opacity="{Binding ElementName=Slider, Path=Value}" />
        <Slider Name="Slider"
                Maximum="1"
                Minimum="0"
                Value="0.5" />
    </StackPanel>
</Window>`
