### ISSUE TITLE
IsVisible vs Visibility in Readme.md documentation

### ISSUE THREAD

**Issue by stevemonaco** [GuOrg/Gu.Wpf.Adorners#33]
I cannot bind `.IsVisible` as described by the samples shown by [Overlay](https://github.com/GuOrg/Gu.Wpf.Adorners#overlay) and [Info](https://github.com/GuOrg/Gu.Wpf.Adorners#info) since `IsVisible` is read-only.

```xml
<Rectangle
	adorners:Info.IsVisible="True"
```
Results in the error message: `Error MC3065 'Info.IsVisible' property is read-only and cannot be set from markup.`

I believe they should be changed to `.Visibility` as mentioned by the 2.0 breaking change.

**Comment by FoggyFinder** [comment]
Yep. Would you mind to open PR or you prefer that someone else fix it ?

**Comment by stevemonaco** [comment]
I can PR it in a day or so, if needed. It looks like the samples were taken from the (now updated) demo apps.

**Comment by FoggyFinder** [comment]
Thank you
