### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by andres15alvarez** [GuOrg/Gu.Wpf.Adorners#54]
I downloaded the latest version, and inserted into a user control
`<UserControl x:Class="Helen.Controls.PasswordBoxControl"`
             `xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"`
             `xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"`
             `xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"` 
             `xmlns:d="http://schemas.microsoft.com/expression/blend/2008"`
             `xmlns:adorners="http://gu.se/Adorners"`
             `xmlns:local="clr-namespace:Helen.Controls"`
             `mc:Ignorable="d" `
             `d:DesignHeight="450" d:DesignWidth="800">`
    `<PasswordBox x:Name="passwordBox" PasswordChanged="PasswordBox_PasswordChanged" adorners:Watermark.Text="Password"/>`
`</UserControl>`
And the Watermark does not appears in intellisense and it's mark like wrong.
This application it's write in .net core 3.1

**Comment by FoggyFinder** [comment]
Does it show a warning after project is compiled?

**Comment by andres15alvarez** [comment]
It show me a warning before compile, i deleted the adorner and compile the project, but when i added the adorner again the waring raised up again

**Comment by andres15alvarez** [comment]
![2021-02-06 (2)](https://user-images.githubusercontent.com/9939646/107125355-dfcfb980-687f-11eb-8617-aa14faaa654b.png)

**Comment by andres15alvarez** [comment]
After compile the project the watermark appears, just ignore the warning.

**Comment by geovanibruno** [comment]
Even after compiling, IntelliSense still complains about attached properties not being found. In my case, `"Text"` and `"VisibleWhen"`.

Is there anything else that can be done?
